name: Build & Deploy via FTP

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Configure base path
        run: |
          set -euo pipefail
          echo "VITE_BASE_PATH=/" >> "$GITHUB_ENV"
          echo "EXPECTED_BASE_PATH=/" >> "$GITHUB_ENV"

      - name: Build site
        run: npm run build

      - name: Generate language-specific pages
        run: npm run postbuild

      - name: Verify built asset base path
        run: node scripts/verify-base-path.mjs "$EXPECTED_BASE_PATH"

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          security: none
          port: ${{ secrets.FTP_PORT }}
          timeout: 3600000
          local-dir: dist
          server-dir: ${{ secrets.FTP_PATH }}
          state-name: ftp-deploy-sync-state-${{ github.ref_name }}.json
